---
title: "Model_Zuocheng"
author: "Zhang"
date: "2025-04-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(openxlsx)
library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
library(timeDate)
```


## Importing Data

```{r pressure, echo=FALSE}

#Importing daily data
daily_data <- read.csv(file="../data/processed/processed_daily_data.csv", header=TRUE)

#Importing hourly data
hourly_data <- read.csv(file="../data/processed/processed_hourly_data.csv", header=TRUE)

#Inspect daily data
nvar <- ncol(daily_data) - 1
nobs <- nrow(daily_data)

#Inspect hourly data
nvar <- ncol(hourly_data) - 1
nobs <- nrow(hourly_data)

```


## Testing and Training Datasets
```{r}



ts_load_hourly <- msts(hourly_data$load_value, 
                           seasonal.periods =c(24,168,8766),
                           start=c(2005,01,01))

ts_load_daily <- msts(daily_data[2:4], 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,01,01))


ts_hourly_train <- subset(ts_load_hourly,
                                   end = length(ts_load_hourly)-365)


ts_hourly_test <- subset(ts_load_hourly,
                                   start = length(ts_load_hourly)-365)


n <- length(ts_load_daily)
h <- 365


ts_daily_train <- window(ts_load_daily, end=c(2009, 365))

ts_daily_test <- window(ts_load_daily, start=c(2010,1))



```






## Initial Plots & Time Series
```{r}

TSplot <- autoplot(ts_load_daily) +
    ggtitle("hourly Load Time Series (2005-2010)") +
    xlab("Year") + 
    ylab("Load") +
    theme_minimal()
plot(TSplot)

#ACF and PACF plots
par(mfrow=c(1,2))
ACF_Plot <- Acf(daily_data$load_daily, lag = 40, plot = TRUE)
PACF_Plot <- Pacf(daily_data$load_daily, lag = 40)
par(mfrow=c(1,1))


```

### Exploring data
```{r}

summary(ts_load_hourly)


ggplot(daily_data, aes(x = load_daily)) +
  geom_histogram(
    aes(y = ..density..),
    bins=50) + 
  geom_density(color="red")

```

## Create some features of the data

### Lagged terms or season terms? Volatality? Weekends?

```{r}

#fit_arima <- auto.arima(ts_daily_train[,1],lambda = TRUE)

#print(fit_arima)
daily_data$date <- as.Date(daily_data$date)

us_years <- as.numeric(format(daily_data$date, "%Y"))
us_holidays <- holidayNYSE(unique(us_years))


Sys.setlocale("LC_ALL", "C")


daily_data <- daily_data %>%
              mutate(lag1 = lag(daily_data$load_daily,1),
                     lag2 = lag(daily_data$load_daily,2),
                     volatility_3d = rollapply(daily_data$load_daily, width = 3, FUN = sd, align = "right", fill = NA),
                     volatility_7d = rollapply(daily_data$load_daily, width = 7, FUN = sd, align = "right", fill = NA))  %>%
  mutate(is_weekend = as.integer(weekdays(date) %in% c("Saturday", "Sunday"))) %>%
  mutate(quarter = quarter(date),
         is_us_holiday = as.integer(date %in% as.Date(us_holidays))) %>%
  drop_na()





```


### Search for parameters
```{r}
grid_search_nnetar_safe <- function(train_data, test_data, 
                                    p_values = 1:2, 
                                    P_values = 0:1, 
                                    K_values = list(c(1,1), c(2,2), c(3,3)), 
                                    h = 60,
                                    repeats = 20) {
  
  results <- list()
  counter <- 1
  
  for (p in p_values) {
    for (P in P_values) {
      for (K in K_values) {
        try({
          # 构建 xreg
          xreg_train <- cbind(fourier(train_data[,1], K = K), train_data[,5:8])
          xreg_test_raw <- cbind(fourier(test_data[,1], K = K, h = h), test_data[1:h, 5:8])
          
          # 获取训练时的列名
          col_order <- colnames(xreg_train)
          
          # 强制统一测试集列名和顺序
          colnames(xreg_test_raw) <- colnames(xreg_train)  # 先改名
          xreg_test <- xreg_test_raw[, col_order]          # 再按顺序排列

          # 建模
          model <- nnetar(train_data[,1], p = p, P = P, xreg = xreg_train, repeats = repeats)
          
          # 预测
          forecast_result <- forecast(model, h = h, xreg = xreg_test)
          
          # 评估
          acc <- accuracy(forecast_result$mean, test_data[1:h, 1])
          
          # 存结果
          results[[counter]] <- tibble(
            p = p,
            P = P,
            K1 = K[1],
            K2 = K[2],
            RMSE = acc["Test set", "RMSE"],
            MAPE = acc["Test set", "MAPE"]
          )
          
          counter <- counter + 1
          
        }, silent = TRUE)  # 有错跳过
      }
    }
  }
  
  # 汇总结果
  results_df <- bind_rows(results)
  results_df <- arrange(results_df, RMSE)
  
  return(results_df)
}
```


```{r}
result_df <- grid_search_nnetar_safe(
  train_data = ts_daily_train,
  test_data = ts_daily_test,
  p_values = 1:3,
  P_values = 0:1,
  K_values = list(c(1,1), c(2,2), c(3,3)),
  h = 60,
  repeats = 20
)

print(result_df)


```


## NN model with data features

```{r NNETAR, echo=TRUE, message=FALSE, warning=FALSE}
#You can play with the different values for p and P, you can also use xreg with Fourier term to model the multiple seasonality


ts_load_daily <- msts(daily_data[-1], 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,01,13))

ts_daily_train <- window(ts_load_daily, end=c(2009, 365))

ts_daily_test <- window(ts_load_daily, start=c(2010,1))


NN_fit <- nnetar(ts_daily_train[,1],
                 p=1,
                 P=1,
                 xreg=cbind(fourier(ts_daily_train[,1], K = c(1,1)),ts_daily_train[,5:8]))


NN_for <- forecast(NN_fit, 
                   h = 60,
                   xreg=cbind(fourier(ts_daily_test[,1], K = c(1,1),h=60),ts_daily_test[1:60,5:8]))




#Plot foresting results
autoplot(NN_for) +
  ylab("Active Power") 


#Plot model + observed data
autoplot(ts_daily_train[,1]) +
  autolayer(NN_for, series="Neural Network",PI=TRUE)+
  ylab("Active Power") 


NN_scores <- accuracy(NN_for$mean,ts_daily_test[,1])

print(NN_scores)

output <- NN_for$mean[1:59]


template <- read_excel("../result/submission_template.xlsx")

template$load[1:length(output)] <- as.numeric(output)

write.csv(template, file = "../result/NN_with_features V4.csv",row.names = FALSE)

```




