---
title: "Models"
author: "YoungZhang"
output: html_document
date: "2025-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=60), tidy=TRUE) 
```

```{r}
library(readxl)
library(openxlsx)
library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
```

## Importing Data

```{r pressure, echo=FALSE}

#Importing daily data
daily_data <- read.csv(file="/home/guest/ForecastingCompetition/data/processed/processed_daily_data.csv", header=TRUE)

#Importing hourly data
hourly_data <- read.csv(file="/home/guest/ForecastingCompetition/data/processed/processed_hourly_data.csv", header=TRUE)

#Inspect daily data
head(daily_data)
nvar <- ncol(daily_data) - 1
nobs <- nrow(daily_data)

#Inspect hourly data
head(hourly_data)
nvar <- ncol(hourly_data) - 1
nobs <- nrow(hourly_data)

```
## Testing and Training Datasets
```{r}


ts_load_hourly <- msts(hourly_data$load_value, 
                           seasonal.periods =c(24,168,8766),
                           start=c(2005,01,01))

ts_load_daily <- msts(daily_data$load_daily, 
                           seasonal.periods =c(7,365.25),
                           start=c(2005,01,01))


ts_hourly_train <- subset(ts_load_hourly,
                                   end = length(ts_load_hourly)-365)


ts_hourly_test <- subset(ts_load_hourly,
                                   start = length(ts_load_hourly)-365)


n <- length(ts_load_daily)
h <- 365


ts_daily_train <- window(ts_load_daily, end=c(2009, 365))

ts_daily_test <- window(ts_load_daily, start=c(2010,1))

```


## Initial Plots & Time Series
```{r}

TSplot <- autoplot(ts_load_daily) +
    ggtitle("Daily Load Time Series (2005-2010)") +
    xlab("Year") + 
    ylab("Load") +
    theme_minimal()
plot(TSplot)

#ACF and PACF plots
par(mfrow=c(1,2))
ACF_Plot <- Acf(daily_data$load_daily, lag = 40, plot = TRUE)
PACF_Plot <- Pacf(daily_data$load_daily, lag = 40)
par(mfrow=c(1,1))

```

## Forecast using Seasonal Naive Method
```{r}

# Seasonal naive on original data
SNAIVE_seas <- snaive(ts_load_daily, h=60)
plot(SNAIVE_seas)

checkresiduals(SNAIVE_seas)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## Write into Excel file
```{r}

write.csv(SNAIVE_seas, file = "seasonal_naive_forecast.csv")

```


## TBATS
```{r}

tbats_fit <- tbats(ts_load_daily)
tbats_forecast <- forecast(tbats_fit, h = 60)
autoplot(tbats_forecast)

```

## Write CSV for tbats
```{r}

write.csv(tbats_forecast, file = "tbats_forecast.csv")

```

## STL + ETS
```{r}

load_stl_ets <- stlf(ts_load_daily, h = 60, method = "ets")
plot(load_stl_ets)

```

## Write CSV for STL + ETS
```{r}

write.csv(load_stl_ets, file = "stlets_forecast.csv")

```

